services:
  - type: web
    name: backend-tasks
    env: node
    plan: starter
    buildCommand: pnpm install --frozen-lockfile && pnpm run build
    startCommand: NODE_OPTIONS=--max-old-space-size=512 pnpm run start:prod
    healthCheckPath: /api
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
